global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape OpenTelemetry Collector metrics
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: ".*grpc_io.*"
        action: drop
