# Morgana Protocol Configuration
# This file configures the behavior of the Morgana agent orchestrator

# Agent configuration
agents:
  # Directory containing agent prompt files
  prompt_dir: ~/.claude/agents

  # Default timeout for agent execution
  default_timeout: 2m

  # Agent-specific timeouts (override default)
  timeouts:
    code-implementer: 5m # Code generation might take longer
    test-specialist: 3m # Test generation is usually faster
    validation-expert: 2m # Validation is typically quick
    sprint-planner: 1m # Planning should be fast

  # Retry configuration for failed agents
  retry:
    enabled: true
    max_attempts: 3
    initial_backoff: 1s
    max_backoff: 30s
    multiplier: 2.0

# Execution configuration
execution:
  # Maximum number of concurrent agent executions
  max_concurrency: 5

  # Default execution mode: sequential or parallel
  default_mode: sequential

  # Queue size for parallel execution
  queue_size: 100

# Telemetry configuration
telemetry:
  # Enable or disable telemetry
  enabled: true

  # Exporter type: stdout, otlp, or none
  exporter: stdout

  # OTLP collector endpoint (for otlp exporter)
  otlp_endpoint: localhost:4317

  # Service name for telemetry
  service_name: morgana-protocol

  # Environment: production, staging, or development
  environment: production

  # Sampling rate (0.0 to 1.0)
  # 0.1 = 10% of traces are sampled
  sampling_rate: 0.1

# Task client configuration
tui:
  # Enable TUI mode
  enabled: true

  # Performance configuration
  performance:
    # Target refresh rate (e.g., "16ms" for 60fps)
    # Reduced to 50ms (20fps) for smoother, less flickery updates
    refresh_rate: 50ms

    # Maximum log lines to keep in memory
    # Reduced for better performance
    max_log_lines: 1000

    # Enable performance optimizations
    optimized_rendering: true

    # Target FPS (frames per second)
    # Reduced for smoother experience
    target_fps: 20

  # Visual configuration
  visual:
    # Color theme configuration
    theme:
      # Theme name: dark, light, or custom
      name: dark

      # Base colors (hex format)
      primary: "#7C3AED" # Violet
      secondary: "#06B6D4" # Cyan
      success: "#10B981" # Emerald
      warning: "#F59E0B" # Amber
      error: "#EF4444" # Red
      info: "#3B82F6" # Blue

      # UI element colors
      background: "#0F172A" # Slate 900
      foreground: "#F1F5F9" # Slate 100
      border: "#334155" # Slate 700
      highlight: "#1E293B" # Slate 800
      muted: "#64748B" # Slate 500

      # Progress bar colors
      progress_bar:
        complete: "#10B981" # Success color
        incomplete: "#64748B" # Muted color
        background: "#334155" # Border color

      # Agent-specific colors
      agent_colors:
        code-implementer: "#10B981" # Green
        sprint-planner: "#3B82F6" # Blue
        test-specialist: "#F59E0B" # Amber
        validation-expert: "#EF4444" # Red
        default: "#64748B" # Slate

    # Show debug information panel
    show_debug_info: false

    # Show timestamps in logs
    show_timestamps: true

    # Use compact display mode
    compact_mode: false

    # Minimum terminal size requirements
    min_width: 80
    min_height: 24

  # Feature flags
  features:
    # Enable log filtering capabilities
    enable_filtering: true

    # Enable log search functionality
    enable_search: true

    # Enable export functionality
    enable_export: false

    # Enable keyboard shortcuts
    enable_keyboard_shortcuts: true

    # Enable mouse interaction
    enable_mouse: true

    # Enable auto-scroll for logs
    enable_auto_scroll: true

  # Event system configuration
  events:
    # Buffer size for event processing
    buffer_size: 1000

    # Event subscription filters (empty = subscribe to all)
    subscription_filters: []

    # Enable event batching for performance
    enable_batching: true

    # Batch size for event processing
    batch_size: 50

    # Batch timeout for event processing
    batch_timeout: 100ms

    # Event processing timeout
    processing_timeout: 5s
# Environment variable overrides:
# - MORGANA_AGENT_DIR: Override agents.prompt_dir
# - MORGANA_MAX_CONCURRENCY: Override execution.max_concurrency
# - MORGANA_OTEL_EXPORTER: Override telemetry.exporter
# - MORGANA_OTEL_ENDPOINT: Override telemetry.otlp_endpoint
# - MORGANA_BRIDGE_PATH: Override task_client.bridge_path
# - MORGANA_MOCK_MODE: Set to "true" to enable mock mode
# - MORGANA_TUI_ENABLED: Set to "true" or "false" to enable/disable TUI
# - MORGANA_TUI_REFRESH_RATE: Override tui.performance.refresh_rate (e.g., "16ms")
# - MORGANA_TUI_MAX_LOG_LINES: Override tui.performance.max_log_lines (integer)
# - MORGANA_TUI_BUFFER_SIZE: Override tui.events.buffer_size (integer)
# - MORGANA_TUI_THEME: Override tui.visual.theme.name ("dark", "light", "custom")
# - MORGANA_TUI_COMPACT_MODE: Set to "true" to enable compact display mode
# - MORGANA_TUI_SHOW_DEBUG: Set to "true" to show debug information
